// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mpem_moments_cpp
Rcpp::List mpem_moments_cpp(const arma::mat& x, int rows, int cols, const arma::mat& mean, const arma::mat& row_precision, const arma::mat& col_precision, double precision_multiplier, const arma::mat& completed, const Rcpp::List& conditional_cov, const arma::vec& weights, int sweeps, double warm_start, bool update_moments);
RcppExport SEXP _SpatMix_mpem_moments_cpp(SEXP xSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP meanSEXP, SEXP row_precisionSEXP, SEXP col_precisionSEXP, SEXP precision_multiplierSEXP, SEXP completedSEXP, SEXP conditional_covSEXP, SEXP weightsSEXP, SEXP sweepsSEXP, SEXP warm_startSEXP, SEXP update_momentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type row_precision(row_precisionSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type col_precision(col_precisionSEXP);
    Rcpp::traits::input_parameter< double >::type precision_multiplier(precision_multiplierSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type completed(completedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type conditional_cov(conditional_covSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type sweeps(sweepsSEXP);
    Rcpp::traits::input_parameter< double >::type warm_start(warm_startSEXP);
    Rcpp::traits::input_parameter< bool >::type update_moments(update_momentsSEXP);
    rcpp_result_gen = Rcpp::wrap(mpem_moments_cpp(x, rows, cols, mean, row_precision, col_precision, precision_multiplier, completed, conditional_cov, weights, sweeps, warm_start, update_moments));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpatMix_mpem_moments_cpp", (DL_FUNC) &_SpatMix_mpem_moments_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpatMix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
