# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mpem_moments_cpp <- function(x, rows, cols, mean, row_precision, col_precision, precision_multiplier, completed, conditional_cov, weights, sweeps = 1L, warm_start = 1.0, update_moments = TRUE) {
    .Call(`_SpatMix_mpem_moments_cpp`, x, rows, cols, mean, row_precision, col_precision, precision_multiplier, completed, conditional_cov, weights, sweeps, warm_start, update_moments)
}

